version: 0.1

phases:
  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm install
  post_build:
    commands:
      - mkdir -p build
      - tar jcf build/notes2-$(date +%Y%m%d%H%m%S).tar.bz2 .gitignore README.md buildspec.yml package.json serverless.yml *.js mocks test
      - npm install -g serverless
      - serverless -v deploy

artifacts:
  files:
    - build*/**
  discard-paths: yes
