version: 0.1

phases:
  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm install
  post_build:
    commands:
      - mkdir -p build
      - npm install -g serverless
      - serverless -v deploy

artifacts:
  files:
    - build*/**
  discard-paths: yes
